/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalTreatmentRouteImport } from './routes/_authenticated/portal.treatment'
import { Route as AuthenticatedPortalRecordsRouteImport } from './routes/_authenticated/portal.records'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalPrescriptionsRouteImport } from './routes/_authenticated/portal.prescriptions'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal.notifications'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedPortalBillingRouteImport } from './routes/_authenticated/portal.billing'
import { Route as AuthenticatedPortalAppointmentsRouteImport } from './routes/_authenticated/portal.appointments'
import { Route as AuthenticatedDashboardRecordsRouteImport } from './routes/_authenticated/dashboard.records'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin.patients'
import { Route as AuthenticatedAdminOngoingTreatmentsRouteImport } from './routes/_authenticated/admin.ongoing-treatments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAdminPatientDetailsPatientIdRouteImport } from './routes/_authenticated/admin.patient-details.$patientId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalTreatmentRoute =
  AuthenticatedPortalTreatmentRouteImport.update({
    id: '/treatment',
    path: '/treatment',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalRecordsRoute =
  AuthenticatedPortalRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPrescriptionsRoute =
  AuthenticatedPortalPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBillingRoute =
  AuthenticatedPortalBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAppointmentsRoute =
  AuthenticatedPortalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedDashboardRecordsRoute =
  AuthenticatedDashboardRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/admin/profile',
    path: '/admin/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOngoingTreatmentsRoute =
  AuthenticatedAdminOngoingTreatmentsRouteImport.update({
    id: '/admin/ongoing-treatments',
    path: '/admin/ongoing-treatments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPatientDetailsPatientIdRoute =
  AuthenticatedAdminPatientDetailsPatientIdRouteImport.update({
    id: '/admin/patient-details/$patientId',
    path: '/admin/patient-details/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/ongoing-treatments': typeof AuthenticatedAdminOngoingTreatmentsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/dashboard/records': typeof AuthenticatedDashboardRecordsRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/records': typeof AuthenticatedPortalRecordsRoute
  '/portal/treatment': typeof AuthenticatedPortalTreatmentRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/patient-details/$patientId': typeof AuthenticatedAdminPatientDetailsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/ongoing-treatments': typeof AuthenticatedAdminOngoingTreatmentsRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/dashboard/records': typeof AuthenticatedDashboardRecordsRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/records': typeof AuthenticatedPortalRecordsRoute
  '/portal/treatment': typeof AuthenticatedPortalTreatmentRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/patient-details/$patientId': typeof AuthenticatedAdminPatientDetailsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/services': typeof ServicesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/ongoing-treatments': typeof AuthenticatedAdminOngoingTreatmentsRoute
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/dashboard/records': typeof AuthenticatedDashboardRecordsRoute
  '/_authenticated/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/_authenticated/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/records': typeof AuthenticatedPortalRecordsRoute
  '/_authenticated/portal/treatment': typeof AuthenticatedPortalTreatmentRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/patient-details/$patientId': typeof AuthenticatedAdminPatientDetailsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/services'
    | '/dashboard'
    | '/portal'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/notifications'
    | '/admin/ongoing-treatments'
    | '/admin/patients'
    | '/admin/profile'
    | '/dashboard/records'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/documents'
    | '/portal/notifications'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/portal/records'
    | '/portal/treatment'
    | '/portal/'
    | '/admin/patient-details/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/services'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/notifications'
    | '/admin/ongoing-treatments'
    | '/admin/patients'
    | '/admin/profile'
    | '/dashboard/records'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/documents'
    | '/portal/notifications'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/portal/records'
    | '/portal/treatment'
    | '/portal'
    | '/admin/patient-details/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/services'
    | '/_authenticated/dashboard'
    | '/_authenticated/portal'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/ongoing-treatments'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/profile'
    | '/_authenticated/dashboard/records'
    | '/_authenticated/portal/appointments'
    | '/_authenticated/portal/billing'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/prescriptions'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/records'
    | '/_authenticated/portal/treatment'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/patient-details/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  ServicesRoute: typeof ServicesRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/treatment': {
      id: '/_authenticated/portal/treatment'
      path: '/treatment'
      fullPath: '/portal/treatment'
      preLoaderRoute: typeof AuthenticatedPortalTreatmentRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/records': {
      id: '/_authenticated/portal/records'
      path: '/records'
      fullPath: '/portal/records'
      preLoaderRoute: typeof AuthenticatedPortalRecordsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/prescriptions': {
      id: '/_authenticated/portal/prescriptions'
      path: '/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof AuthenticatedPortalPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/billing': {
      id: '/_authenticated/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof AuthenticatedPortalBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/appointments': {
      id: '/_authenticated/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof AuthenticatedPortalAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/dashboard/records': {
      id: '/_authenticated/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof AuthenticatedDashboardRecordsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ongoing-treatments': {
      id: '/_authenticated/admin/ongoing-treatments'
      path: '/admin/ongoing-treatments'
      fullPath: '/admin/ongoing-treatments'
      preLoaderRoute: typeof AuthenticatedAdminOngoingTreatmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/patient-details/$patientId': {
      id: '/_authenticated/admin/patient-details/$patientId'
      path: '/admin/patient-details/$patientId'
      fullPath: '/admin/patient-details/$patientId'
      preLoaderRoute: typeof AuthenticatedAdminPatientDetailsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardRecordsRoute: typeof AuthenticatedDashboardRecordsRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardRecordsRoute: AuthenticatedDashboardRecordsRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAppointmentsRoute: typeof AuthenticatedPortalAppointmentsRoute
  AuthenticatedPortalBillingRoute: typeof AuthenticatedPortalBillingRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalPrescriptionsRoute: typeof AuthenticatedPortalPrescriptionsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalRecordsRoute: typeof AuthenticatedPortalRecordsRoute
  AuthenticatedPortalTreatmentRoute: typeof AuthenticatedPortalTreatmentRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAppointmentsRoute: AuthenticatedPortalAppointmentsRoute,
  AuthenticatedPortalBillingRoute: AuthenticatedPortalBillingRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalPrescriptionsRoute: AuthenticatedPortalPrescriptionsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalRecordsRoute: AuthenticatedPortalRecordsRoute,
  AuthenticatedPortalTreatmentRoute: AuthenticatedPortalTreatmentRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOngoingTreatmentsRoute: typeof AuthenticatedAdminOngoingTreatmentsRoute
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminPatientDetailsPatientIdRoute: typeof AuthenticatedAdminPatientDetailsPatientIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOngoingTreatmentsRoute:
    AuthenticatedAdminOngoingTreatmentsRoute,
  AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminPatientDetailsPatientIdRoute:
    AuthenticatedAdminPatientDetailsPatientIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  ServicesRoute: ServicesRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
